## Introduction
 the popularity of more powerful libraries such as PyToch and TensorFlow, they are not easy to use and have a steep learning curve. So, for people who are just starting to learn deep learning, there is no better library to use other than the Keras library.

Keras is a high-level API for building deep learning models. It has gained favor for its ease of use and syntactic simplicity facilitating fast development.

## Objectives
* How to use the Keras library to build a regression model
* Download and clean the data set
* Build a neural network
* Train and test the network

In [ ]:
# All Libraries required for this lab are listed below.

!pip install numpy==2.0.2
!pip install pandas==2.2.2
!pip install tensorflow_cpu==2.18.0

Requirement already satisfied: numpy==2.0.2 in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas==2.2.2 in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.17.0)
Collecting tensorflow_cpu==2.18.0
  Downloading tensorflow_cpu-2.18.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (1.17.3)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (1.74.0)
Collecting tensorboard<2.19,>=2.18 (from tensorflow_cpu==2.18.0)
  Downloading tensorboard-2.18.0-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (3.10.0)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu==2.18.0) (3.14.0)
Collecting ml-dtypes<0.5.0,>=0.4.0 (from tensorflow_cpu==2.18.0)
  Downloading ml_dtypes-0.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow_cpu==2.18.0) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow_cpu==2.18.0) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow_cpu==2.18.0) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow_cpu==2.18.0) (0.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (2025.8.3)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0) (3.9)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow_cpu==2.18.0) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow_cpu==2.18.0) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow_cpu==2.18.0) (0.1.2)
Downloading tensorflow_cpu-2.18.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (230.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 230.3/230.3 MB 5.9 MB/s eta 0:00:00
Downloading ml_dtypes-0.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 59.8 MB/s eta 0:00:00
Downloading tensorboard-2.18.0-py3-none-any.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 81.7 MB/s eta 0:00:00
Installing collected packages: ml-dtypes, tensorboard, tensorflow_cpu
  Attempting uninstall: ml-dtypes
    Found existing installation: ml_dtypes 0.5.3
    Uninstalling ml_dtypes-0.5.3:
      Successfully uninstalled ml_dtypes-0.5.3
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.19.0
    Uninstalling tensorboard-2.19.0:
      Successfully uninstalled tensorboard-2.19.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorstore 0.1.76 requires ml_dtypes>=0.5.0, but you have ml-dtypes 0.4.1 which is incompatible.
tensorflow 2.19.0 requires ml-dtypes<1.0.0,>=0.5.1, but you have ml-dtypes 0.4.1 which is incompatible.
tensorflow 2.19.0 requires tensorboard~=2.19.0, but you have tensorboard 2.18.0 which is incompatible.
Successfully installed ml-dtypes-0.4.1 tensorboard-2.18.0 tensorflow_cpu-2.18.0

#### To use Keras, you will also need to install a backend framework – such as TensorFlow.

If you install TensorFlow 2.16 or above, it will install Keras by default.

We are using the CPU version of tensorflow since we are dealing with smaller datasets.
You may install the GPU version of tensorflow on your machine to accelarate the processing of larger datasets

#### Suppress the tensorflow warning messages
We use the following code to  suppress the warning messages due to use of CPU architechture for tensoflow.

In [ ]:
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [ ]:
import pandas as pd
import numpy as np
import keras

import warnings
warnings.simplefilter('ignore', FutureWarning)

<strong>The dataset is about the compressive strength of different samples of concrete based on the volumes of the different ingredients that were used to make them. Ingredients include:</strong>

* Cement
* Blast furnace slag
* Fly ash
* Water
* Superplasticizer
* Coarse aggregate
* Fine aggregate

## Download and Clean the Data Set

In [ ]:
filepath='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv'
concrete_data = pd.read_csv(filepath)

concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

So the first concrete sample has 540 cubic meter of cement, 0 cubic meter of blast furnace slag, 0 cubic meter of fly ash, 162 cubic meter of water, 2.5 cubic meter of superplaticizer, 1040 cubic meter of coarse aggregate, 676 cubic meter of fine aggregate. Such a concrete mix which is 28 days old, has a compressive strength of 79.99 MPa.

#### Let's check how many data points we have

In [ ]:
concrete_data.shape

(1030, 9)

So, there are approximately 1000 samples to train our model on. Because of the few samples, we have to be careful not to overfit the training data.

In [ ]:
#Let's check the dataset for any missing values.
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [ ]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

The data looks very clean and is ready to be used to build our model.

#### Split data into predictors and target
The target variable in this problem is the concrete sample strength. Therefore, our predictors will be all the other columns.

In [ ]:
concrete_data_columns = concrete_data.columns

In [ ]:
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

Let's do a quick sanity check of the predictors and the target dataframes.

In [ ]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [ ]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

the last step is to normalize the data by substracting the mean and dividing by the standard deviation.

In [ ]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

Let's save the number of predictors to n_cols since we will need this number when building our network.

In [ ]:
n_cols = predictors_norm.shape[1] # number of predictors

##  Import Keras Packages

##### Let's import the rest of the packages from the Keras library that we will need to build our regression model.

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input

## Build a Neural Network

a function that defines our regression model for us so that we can conveniently call it to create our model.

In [ ]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))

    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

The above function create a model that has two hidden layers, each of 50 hidden units.

##Train and Test the Network

In [ ]:
# build the model
model = regression_model()

Next, we will train and test the model at the same time using the fit method. We will leave out 30% of the data for validation and we will train the model for 100 epochs.

In [ ]:
# fit the model
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 2s - 76ms/step - loss: 1661.1423 - val_loss: 1166.2311
Epoch 2/100
23/23 - 0s - 18ms/step - loss: 1509.8994 - val_loss: 1050.0156
Epoch 3/100
23/23 - 0s - 14ms/step - loss: 1280.8727 - val_loss: 877.4674
Epoch 4/100
23/23 - 0s - 6ms/step - loss: 956.1530 - val_loss: 657.5986
Epoch 5/100
23/23 - 0s - 8ms/step - loss: 610.0024 - val_loss: 435.6628
Epoch 6/100
23/23 - 0s - 12ms/step - loss: 359.3704 - val_loss: 284.0742
Epoch 7/100
23/23 - 0s - 7ms/step - loss: 267.1884 - val_loss: 217.0011
Epoch 8/100
23/23 - 0s - 15ms/step - loss: 238.2930 - val_loss: 193.9499
Epoch 9/100
23/23 - 0s - 11ms/step - loss: 222.1221 - val_loss: 181.5575
Epoch 10/100
23/23 - 0s - 13ms/step - loss: 209.4364 - val_loss: 177.5397
Epoch 11/100
23/23 - 0s - 12ms/step - loss: 199.9795 - val_loss: 173.5096
Epoch 12/100
23/23 - 0s - 11ms/step - loss: 192.1285 - val_loss: 168.1465
Epoch 13/100
23/23 - 0s - 10ms/step - loss: 185.9230 - val_loss: 164.5346
Epoch 14/100
23/23 - 0s - 17ms/step - loss: 180.7451 - val_loss: 163.0606
Epoch 15/100
23/23 - 0s - 14ms/step - loss: 175.7125 - val_loss: 158.5157
Epoch 16/100
23/23 - 0s - 21ms/step - loss: 171.6422 - val_loss: 156.0214
Epoch 17/100
23/23 - 0s - 6ms/step - loss: 167.8564 - val_loss: 154.8630
Epoch 18/100
23/23 - 0s - 6ms/step - loss: 165.2072 - val_loss: 151.5804
Epoch 19/100
23/23 - 0s - 7ms/step - loss: 161.7340 - val_loss: 151.1046
Epoch 20/100
23/23 - 0s - 13ms/step - loss: 159.1252 - val_loss: 149.1342
Epoch 21/100
23/23 - 0s - 13ms/step - loss: 156.8929 - val_loss: 149.6535
Epoch 22/100
23/23 - 0s - 6ms/step - loss: 154.4881 - val_loss: 149.4766
Epoch 23/100
23/23 - 0s - 6ms/step - loss: 152.9832 - val_loss: 146.7960
Epoch 24/100
23/23 - 0s - 14ms/step - loss: 150.8775 - val_loss: 147.9540
Epoch 25/100
23/23 - 0s - 13ms/step - loss: 148.8898 - val_loss: 146.8153
Epoch 26/100
23/23 - 0s - 7ms/step - loss: 147.0424 - val_loss: 143.9860
Epoch 27/100
23/23 - 0s - 6ms/step - loss: 145.5620 - val_loss: 148.8997
Epoch 28/100
23/23 - 0s - 8ms/step - loss: 144.6517 - val_loss: 145.0771
Epoch 29/100
23/23 - 0s - 12ms/step - loss: 142.5839 - val_loss: 144.7833
Epoch 30/100
23/23 - 0s - 7ms/step - loss: 140.7372 - val_loss: 144.1228
Epoch 31/100
23/23 - 0s - 13ms/step - loss: 139.6170 - val_loss: 143.9591
Epoch 32/100
23/23 - 0s - 7ms/step - loss: 138.2505 - val_loss: 145.2335
Epoch 33/100
23/23 - 0s - 13ms/step - loss: 136.5892 - val_loss: 143.4615
Epoch 34/100
23/23 - 0s - 6ms/step - loss: 136.3173 - val_loss: 142.0264
Epoch 35/100
23/23 - 0s - 6ms/step - loss: 134.2708 - val_loss: 144.8871
Epoch 36/100
23/23 - 0s - 6ms/step - loss: 133.1834 - val_loss: 145.0328
Epoch 37/100
23/23 - 0s - 6ms/step - loss: 132.3553 - val_loss: 145.5113
Epoch 38/100
23/23 - 0s - 14ms/step - loss: 130.1039 - val_loss: 143.9218
Epoch 39/100
23/23 - 0s - 12ms/step - loss: 128.6527 - val_loss: 144.9339
Epoch 40/100
23/23 - 0s - 6ms/step - loss: 127.9280 - val_loss: 143.3361
Epoch 41/100
23/23 - 0s - 6ms/step - loss: 125.9958 - val_loss: 142.2735
Epoch 42/100
23/23 - 0s - 6ms/step - loss: 124.3382 - val_loss: 142.3548
Epoch 43/100
23/23 - 0s - 13ms/step - loss: 123.0616 - val_loss: 142.0633
Epoch 44/100
23/23 - 0s - 7ms/step - loss: 121.5962 - val_loss: 138.3857
Epoch 45/100
23/23 - 0s - 6ms/step - loss: 119.6277 - val_loss: 141.5682
Epoch 46/100
23/23 - 0s - 6ms/step - loss: 118.2628 - val_loss: 141.5227
Epoch 47/100
23/23 - 0s - 6ms/step - loss: 116.7803 - val_loss: 139.0442
Epoch 48/100
23/23 - 0s - 6ms/step - loss: 114.8615 - val_loss: 139.4222
Epoch 49/100
23/23 - 0s - 14ms/step - loss: 113.1141 - val_loss: 136.7828
Epoch 50/100
23/23 - 0s - 12ms/step - loss: 112.1809 - val_loss: 139.3558
Epoch 51/100
23/23 - 0s - 6ms/step - loss: 109.9398 - val_loss: 133.6265
Epoch 52/100
23/23 - 0s - 6ms/step - loss: 109.6142 - val_loss: 135.3700
Epoch 53/100
23/23 - 0s - 7ms/step - loss: 105.6630 - val_loss: 136.4983
Epoch 54/100
23/23 - 0s - 13ms/step - loss: 103.6504 - val_loss: 133.7913
Epoch 55/100
23/23 - 0s - 12ms/step - loss: 101.7084 - val_loss: 130.8824
Epoch 56/100
23/23 - 0s - 14ms/step - loss: 99.4996 - val_loss: 134.2418
Epoch 57/100
23/23 - 0s - 12ms/step - loss: 96.8752 - val_loss: 128.4511
Epoch 58/100
23/23 - 0s - 13ms/step - loss: 94.3007 - val_loss: 129.3928
Epoch 59/100
23/23 - 0s - 6ms/step - loss: 91.3548 - val_loss: 125.4594
Epoch 60/100
23/23 - 0s - 6ms/step - loss: 88.5610 - val_loss: 124.4884
Epoch 61/100
23/23 - 0s - 7ms/step - loss: 85.9863 - val_loss: 128.0568
Epoch 62/100
23/23 - 0s - 15ms/step - loss: 83.5531 - val_loss: 122.5000
Epoch 63/100
23/23 - 0s - 12ms/step - loss: 80.4448 - val_loss: 117.4814
Epoch 64/100
23/23 - 0s - 14ms/step - loss: 77.5822 - val_loss: 126.3259
Epoch 65/100
23/23 - 0s - 9ms/step - loss: 74.8067 - val_loss: 117.5991
Epoch 66/100
23/23 - 0s - 13ms/step - loss: 72.4552 - val_loss: 120.8140
Epoch 67/100
23/23 - 0s - 14ms/step - loss: 69.8849 - val_loss: 118.0353
Epoch 68/100
23/23 - 0s - 13ms/step - loss: 67.6028 - val_loss: 118.5927
Epoch 69/100
23/23 - 0s - 11ms/step - loss: 65.7313 - val_loss: 120.2324
Epoch 70/100
23/23 - 0s - 12ms/step - loss: 63.6680 - val_loss: 117.1835
Epoch 71/100
23/23 - 0s - 6ms/step - loss: 62.2804 - val_loss: 121.3367
Epoch 72/100
23/23 - 0s - 7ms/step - loss: 60.1567 - val_loss: 117.8137
Epoch 73/100
23/23 - 0s - 13ms/step - loss: 57.9786 - val_loss: 113.2983
Epoch 74/100
23/23 - 0s - 7ms/step - loss: 56.3655 - val_loss: 111.9111
Epoch 75/100
23/23 - 0s - 12ms/step - loss: 54.4162 - val_loss: 113.1371
Epoch 76/100
23/23 - 0s - 13ms/step - loss: 53.0108 - val_loss: 111.2347
Epoch 77/100
23/23 - 0s - 6ms/step - loss: 52.1994 - val_loss: 127.3953
Epoch 78/100
23/23 - 0s - 14ms/step - loss: 51.4766 - val_loss: 114.4989
Epoch 79/100
23/23 - 0s - 12ms/step - loss: 48.6167 - val_loss: 111.1962
Epoch 80/100
23/23 - 0s - 9ms/step - loss: 47.9615 - val_loss: 112.2023
Epoch 81/100
23/23 - 0s - 12ms/step - loss: 46.6312 - val_loss: 110.7281
Epoch 82/100
23/23 - 0s - 13ms/step - loss: 45.4563 - val_loss: 121.8241
Epoch 83/100
23/23 - 0s - 12ms/step - loss: 44.5970 - val_loss: 111.8255
Epoch 84/100
23/23 - 0s - 14ms/step - loss: 43.4241 - val_loss: 124.4244
Epoch 85/100
23/23 - 0s - 12ms/step - loss: 42.8006 - val_loss: 108.0410
Epoch 86/100
23/23 - 0s - 13ms/step - loss: 42.2501 - val_loss: 118.6788
Epoch 87/100
23/23 - 0s - 13ms/step - loss: 41.3733 - val_loss: 120.8314
Epoch 88/100
23/23 - 0s - 6ms/step - loss: 40.6105 - val_loss: 114.3949
Epoch 89/100
23/23 - 0s - 13ms/step - loss: 39.5214 - val_loss: 118.7715
Epoch 90/100
23/23 - 0s - 14ms/step - loss: 38.8283 - val_loss: 122.6150
Epoch 91/100
23/23 - 0s - 14ms/step - loss: 38.2930 - val_loss: 121.8814
Epoch 92/100
23/23 - 0s - 13ms/step - loss: 38.0442 - val_loss: 117.8850
Epoch 93/100
23/23 - 0s - 12ms/step - loss: 37.6551 - val_loss: 120.0948
Epoch 94/100
23/23 - 0s - 7ms/step - loss: 37.0169 - val_loss: 114.7394
Epoch 95/100
23/23 - 0s - 6ms/step - loss: 37.0979 - val_loss: 119.0258
Epoch 96/100
23/23 - 0s - 6ms/step - loss: 35.5610 - val_loss: 122.0486
Epoch 97/100
23/23 - 0s - 6ms/step - loss: 35.4731 - val_loss: 128.5823
Epoch 98/100
23/23 - 0s - 6ms/step - loss: 35.5790 - val_loss: 110.5801
Epoch 99/100
23/23 - 0s - 6ms/step - loss: 34.8312 - val_loss: 118.5252
Epoch 100/100
23/23 - 0s - 6ms/step - loss: 34.5898 - val_loss: 118.4375

*Now using the same dateset,try to recreate regression model featuring five hidden layers, each with 50 nodes and ReLU activation functions, a single output layer, optimized using the Adam optimizer.*

In [ ]:
def regression_model():
    input_colm = predictors_norm.shape[1] # Number of input features
    # create model
    model = Sequential()
    model.add(Input(shape=(input_colm,)))  # Set the number of input features
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))  # Output layer

    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

*Train and evaluate the model simultaneously using the fit() method by reserving 10% of the data for validation and training the model for 100 epochs*

In [ ]:
# build the model
model = regression_model()
model.fit(predictors_norm, target, validation_split=0.1, epochs=100, verbose=2)

Epoch 1/100
29/29 - 2s - 82ms/step - loss: 1512.1696 - val_loss: 936.2356
Epoch 2/100
29/29 - 0s - 14ms/step - loss: 625.3254 - val_loss: 325.3275
Epoch 3/100
29/29 - 0s - 11ms/step - loss: 243.1626 - val_loss: 218.6601
Epoch 4/100
29/29 - 0s - 10ms/step - loss: 203.8357 - val_loss: 189.1303
Epoch 5/100
29/29 - 0s - 5ms/step - loss: 180.5589 - val_loss: 175.0406
Epoch 6/100
29/29 - 0s - 5ms/step - loss: 163.2351 - val_loss: 160.7077
Epoch 7/100
29/29 - 0s - 6ms/step - loss: 148.0456 - val_loss: 146.1484
Epoch 8/100
29/29 - 0s - 10ms/step - loss: 132.9905 - val_loss: 134.2872
Epoch 9/100
29/29 - 0s - 10ms/step - loss: 120.1224 - val_loss: 114.4414
Epoch 10/100
29/29 - 0s - 5ms/step - loss: 105.4518 - val_loss: 117.0876
Epoch 11/100
29/29 - 0s - 5ms/step - loss: 89.8941 - val_loss: 123.7556
Epoch 12/100
29/29 - 0s - 5ms/step - loss: 78.1472 - val_loss: 92.9071
Epoch 13/100
29/29 - 0s - 5ms/step - loss: 68.4039 - val_loss: 83.7644
Epoch 14/100
29/29 - 0s - 14ms/step - loss: 58.0876 - val_loss: 88.7755
Epoch 15/100
29/29 - 0s - 9ms/step - loss: 52.0166 - val_loss: 65.6753
Epoch 16/100
29/29 - 0s - 10ms/step - loss: 47.4770 - val_loss: 55.6272
Epoch 17/100
29/29 - 0s - 11ms/step - loss: 43.2721 - val_loss: 48.7037
Epoch 18/100
29/29 - 0s - 10ms/step - loss: 38.6827 - val_loss: 46.4913
Epoch 19/100
29/29 - 0s - 10ms/step - loss: 40.5459 - val_loss: 50.8188
Epoch 20/100
29/29 - 0s - 12ms/step - loss: 36.3993 - val_loss: 36.3157
Epoch 21/100
29/29 - 0s - 5ms/step - loss: 32.5501 - val_loss: 34.0680
Epoch 22/100
29/29 - 0s - 11ms/step - loss: 31.6908 - val_loss: 32.0273
Epoch 23/100
29/29 - 0s - 5ms/step - loss: 29.9277 - val_loss: 31.4175
Epoch 24/100
29/29 - 0s - 12ms/step - loss: 29.0725 - val_loss: 31.3476
Epoch 25/100
29/29 - 0s - 5ms/step - loss: 27.4676 - val_loss: 34.4340
Epoch 26/100
29/29 - 0s - 5ms/step - loss: 27.2198 - val_loss: 31.7630
Epoch 27/100
29/29 - 0s - 5ms/step - loss: 26.5435 - val_loss: 26.5966
Epoch 28/100
29/29 - 0s - 5ms/step - loss: 25.2055 - val_loss: 26.7682
Epoch 29/100
29/29 - 0s - 5ms/step - loss: 24.1066 - val_loss: 28.9484
Epoch 30/100
29/29 - 0s - 11ms/step - loss: 23.8752 - val_loss: 28.5408
Epoch 31/100
29/29 - 0s - 9ms/step - loss: 24.2386 - val_loss: 30.1916
Epoch 32/100
29/29 - 0s - 10ms/step - loss: 22.8271 - val_loss: 26.3673
Epoch 33/100
29/29 - 0s - 12ms/step - loss: 24.3111 - val_loss: 27.3045
Epoch 34/100
29/29 - 0s - 9ms/step - loss: 22.4793 - val_loss: 26.8274
Epoch 35/100
29/29 - 0s - 10ms/step - loss: 21.7197 - val_loss: 25.7668
Epoch 36/100
29/29 - 0s - 10ms/step - loss: 20.4712 - val_loss: 27.3774
Epoch 37/100
29/29 - 0s - 5ms/step - loss: 20.0749 - val_loss: 25.1226
Epoch 38/100
29/29 - 0s - 11ms/step - loss: 20.6091 - val_loss: 27.3879
Epoch 39/100
29/29 - 0s - 5ms/step - loss: 20.1644 - val_loss: 22.8027
Epoch 40/100
29/29 - 0s - 5ms/step - loss: 19.3562 - val_loss: 25.2178
Epoch 41/100
29/29 - 0s - 5ms/step - loss: 18.6053 - val_loss: 25.9367
Epoch 42/100
29/29 - 0s - 11ms/step - loss: 19.1400 - val_loss: 22.7562
Epoch 43/100
29/29 - 0s - 5ms/step - loss: 19.8025 - val_loss: 23.8451
Epoch 44/100
29/29 - 0s - 6ms/step - loss: 18.7378 - val_loss: 24.5255
Epoch 45/100
29/29 - 0s - 9ms/step - loss: 17.2108 - val_loss: 22.8305
Epoch 46/100
29/29 - 0s - 6ms/step - loss: 17.5210 - val_loss: 21.6646
Epoch 47/100
29/29 - 0s - 5ms/step - loss: 19.1426 - val_loss: 22.5522
Epoch 48/100
29/29 - 0s - 6ms/step - loss: 16.9585 - val_loss: 21.7068
Epoch 49/100
29/29 - 0s - 10ms/step - loss: 16.7759 - val_loss: 24.7372
Epoch 50/100
29/29 - 0s - 5ms/step - loss: 15.8426 - val_loss: 22.7428
Epoch 51/100
29/29 - 0s - 10ms/step - loss: 15.3387 - val_loss: 21.7276
Epoch 52/100
29/29 - 0s - 5ms/step - loss: 16.2059 - val_loss: 23.0050
Epoch 53/100
29/29 - 0s - 10ms/step - loss: 15.4763 - val_loss: 21.7137
Epoch 54/100
29/29 - 0s - 6ms/step - loss: 17.1763 - val_loss: 26.8145
Epoch 55/100
29/29 - 0s - 9ms/step - loss: 15.3889 - val_loss: 21.3236
Epoch 56/100
29/29 - 0s - 5ms/step - loss: 14.7985 - val_loss: 20.4035
Epoch 57/100
29/29 - 0s - 12ms/step - loss: 16.1591 - val_loss: 20.9263
Epoch 58/100
29/29 - 0s - 9ms/step - loss: 15.4175 - val_loss: 20.8434
Epoch 59/100
29/29 - 0s - 10ms/step - loss: 14.9731 - val_loss: 22.7329
Epoch 60/100
29/29 - 0s - 6ms/step - loss: 14.2444 - val_loss: 19.3313
Epoch 61/100
29/29 - 0s - 5ms/step - loss: 14.2234 - val_loss: 22.6807
Epoch 62/100
29/29 - 0s - 10ms/step - loss: 15.2124 - val_loss: 19.7480
Epoch 63/100
29/29 - 0s - 6ms/step - loss: 13.5221 - val_loss: 19.8196
Epoch 64/100
29/29 - 0s - 5ms/step - loss: 13.4090 - val_loss: 20.9417
Epoch 65/100
29/29 - 0s - 5ms/step - loss: 14.3228 - val_loss: 20.7236
Epoch 66/100
29/29 - 0s - 14ms/step - loss: 15.5883 - val_loss: 20.8250
Epoch 67/100
29/29 - 0s - 9ms/step - loss: 13.0412 - val_loss: 18.1817
Epoch 68/100
29/29 - 0s - 10ms/step - loss: 13.3687 - val_loss: 18.8709
Epoch 69/100
29/29 - 0s - 10ms/step - loss: 13.0427 - val_loss: 19.2606
Epoch 70/100
29/29 - 0s - 12ms/step - loss: 12.9887 - val_loss: 17.9697
Epoch 71/100
29/29 - 0s - 9ms/step - loss: 13.4755 - val_loss: 22.2658
Epoch 72/100
29/29 - 0s - 10ms/step - loss: 12.6580 - val_loss: 19.3056
Epoch 73/100
29/29 - 0s - 9ms/step - loss: 12.5600 - val_loss: 18.0775
Epoch 74/100
29/29 - 0s - 5ms/step - loss: 13.2720 - val_loss: 18.5057
Epoch 75/100
29/29 - 0s - 10ms/step - loss: 12.9195 - val_loss: 17.4490
Epoch 76/100
29/29 - 0s - 10ms/step - loss: 12.3116 - val_loss: 16.9218
Epoch 77/100
29/29 - 0s - 5ms/step - loss: 12.5512 - val_loss: 16.9671
Epoch 78/100
29/29 - 0s - 10ms/step - loss: 12.1966 - val_loss: 17.0008
Epoch 79/100
29/29 - 0s - 5ms/step - loss: 11.9618 - val_loss: 17.4442
Epoch 80/100
29/29 - 0s - 10ms/step - loss: 12.1868 - val_loss: 16.9079
Epoch 81/100
29/29 - 0s - 10ms/step - loss: 11.4343 - val_loss: 17.8767
Epoch 82/100
29/29 - 0s - 10ms/step - loss: 12.4698 - val_loss: 16.9304
Epoch 83/100
29/29 - 0s - 10ms/step - loss: 12.1886 - val_loss: 17.0134
Epoch 84/100
29/29 - 0s - 5ms/step - loss: 11.8676 - val_loss: 15.5873
Epoch 85/100
29/29 - 0s - 11ms/step - loss: 11.5897 - val_loss: 17.9487
Epoch 86/100
29/29 - 0s - 10ms/step - loss: 11.8705 - val_loss: 15.3518
Epoch 87/100
29/29 - 0s - 10ms/step - loss: 12.1062 - val_loss: 18.0173
Epoch 88/100
29/29 - 0s - 6ms/step - loss: 11.0548 - val_loss: 15.6368
Epoch 89/100
29/29 - 0s - 5ms/step - loss: 10.7126 - val_loss: 15.5007
Epoch 90/100
29/29 - 0s - 11ms/step - loss: 12.9857 - val_loss: 16.0916
Epoch 91/100
29/29 - 0s - 11ms/step - loss: 10.8673 - val_loss: 16.1770
Epoch 92/100
29/29 - 0s - 9ms/step - loss: 12.1497 - val_loss: 15.7260
Epoch 93/100
29/29 - 0s - 11ms/step - loss: 11.4136 - val_loss: 14.9799
Epoch 94/100
29/29 - 0s - 10ms/step - loss: 10.5991 - val_loss: 14.6068
Epoch 95/100
29/29 - 0s - 6ms/step - loss: 10.2408 - val_loss: 14.7363
Epoch 96/100
29/29 - 0s - 5ms/step - loss: 10.9772 - val_loss: 15.1087
Epoch 97/100
29/29 - 0s - 5ms/step - loss: 12.0372 - val_loss: 14.0200
Epoch 98/100
29/29 - 0s - 11ms/step - loss: 14.4724 - val_loss: 24.5669
Epoch 99/100
29/29 - 0s - 5ms/step - loss: 11.5138 - val_loss: 14.5098
Epoch 100/100
29/29 - 0s - 5ms/step - loss: 12.3865 - val_loss: 14.9993